name: My First Workflow
'on': push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v7
    - name: List and Readfile
      run: |
          echo "my first Github Actions"
             ls -ltra
             cat README.md

     # - name: List files
     #   run: ls
     # - name: show content of the files
     #   run: cat README.md
    - name: Generate ASCII Artbook
      run: cowsay -f dragon "Run for cover, i am a Dragon....RAWR" >> dragon.txt
 
